Gmn/urls.py
from django.contrib import admin
from django.urls import path
from gayrimenkul import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('gayrimenkul/',include(('gayrimenkul.urls', 'gayrimenkul'), namespace='gayrimenkul')),
    path('',views.index,name="index"),
    path('user/',include(('user.urls', 'user'),namespace='user')),
    path('administrator/',include(('administrator.urls','administrator'),namespace='administrator')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

administrator/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.administrator,name="administrator"),
    path('users',views.users,name="users"),
]

gayrimenkul/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name="index"),
    path('create',views.post_create,name="create"),
    path('detail/<str:slug>',views.post_detail,name="detail"),
    path('list',views.post_list,name="list"),
    path('update/<str:slug>',views.post_update,name="update"),
    path('delete/<str:slug>',views.post_delete,name="delete"),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
#from .views import RegisterView
app_name = "user"


urlpatterns = [
    path('login/',views.loginUser,name = "login"),
    path('register/',views.register,name = "register"),
    path('logout/',views.logoutUser,name = "logout"),
    path('panel/<str:username>',views.userPanel,name="userPanel"),
    path('code/',views.CreateRegistrationCode,name="code"),
]

user/forms.py
from django import forms
from .models import User, UserUpdateModel
from django.contrib.auth.forms import ReadOnlyPasswordHashField, UserChangeForm
     
class UserAdminCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username','email','cep_telefonu')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email','full_name','is_telefonu','cep_telefonu',"registration_code",'password', 'active', 'admin')

    def clean_password(self):
        return self.initial["password"]


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label = "Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Password Confirmation", widget = forms.PasswordInput)
    class Meta:
        model = User
        fields = ["username"]
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Password do not match")
        return password2
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.clean_data["password1"])
        if commit:
            user.save()
        return user

class LoginForm(forms.Form):
    username = forms.CharField(label = 'Username')
    password = forms.CharField(widget=forms.PasswordInput) 

class RegisterForm(forms.Form):
    class Meta:
        model = User
        fields = ['username','email','cep_telefonu','is_telefonu','full_name','password','confirm','registration_code']
    def __init__(self,*args,**kwargs):
        super(RegisterForm, self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs={'class':'form-control'}

    username = forms.CharField(label = 'Username')
    email = forms.EmailField()
    full_name = forms.CharField(label = 'Ad Soyad')
    cep_telefonu = forms.CharField(label= 'Cep Telefonu')
    is_telefonu = forms.CharField(label = 'İş Telefonu', required=False)
    password = forms.CharField(widget = forms.PasswordInput)
    confirm = forms.CharField(label='Confirm Password',widget = forms.PasswordInput)
    registration_code = forms.CharField(required = True, label = "Kayıt Onay Kodu")
    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")
        email = self.cleaned_data.get("email")
        full_name = self.cleaned_data.get("full_name")
        registration_code = self.cleaned_data.get("registration_code")
        cep_telefonu = self.cleaned_data.get("cep_telefonu")
        is_telefonu = self.cleaned_data.get("is_telefonu")
        if password and confirm and password != confirm:
            raise forms.ValidationError("Passwords Does Not Match")
        if email == False:
            raise forms.ValidationError("A Valid Email Address")
        values = {
            "username" : username,
            "password" : password,
            "email" : email,
            "full_name" : full_name,
            "registration_code":registration_code,
            "cep_telefonu":cep_telefonu,
            "is_telefonu":is_telefonu
        }
        return values



class UserUpdateForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)
    confirm = forms.CharField(label='Confirm Password',widget = forms.PasswordInput)
    class Meta:
        model = UserUpdateModel
        fields = {'email',
            'full_name',
            'cep_telefonu',
            'is_telefonu',}
    
 

templates/admin.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Bootstrap CSS -->
     <link rel="shortcut icon" type="image/png" href="/media/favicon.png"/>
     <link href="{% static 'fontawesome-free-5.13.0-web/css/all.css' %}" rel="stylesheet">
    <title>Gayrimenkul</title>
  </head>
  <body>
  
	{% if request.user.is_admin %}
	<nav class="navbar navbar-expand-sm navbar-light bg-light">
	  <a class="navbar-brand" href="/">Gayrimenkul</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
		
		  <li class="nav-item">
			<a class="nav-link" href="{% url 'administrator:administrator' %}">İlanlar</a>
		  </li>
		  <li class="nav-item">
			<a class="nav-link" href="{% url 'administrator:users' %}">Kullanıcılar</a>
		  </li>
		 
		</ul>
		<ul class="navbar-nav ml-auto"> 
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user:userPanel' request.user%}">{{request.user}}</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user:code' %}">Üye Davet Kodu</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</a>
			</li>
		</ul>
	  </div>
	</nav>
	{% endif %}

<div class="container" style="margin-top:15px;text-align:center;width:100%;">
{% include 'messages.html' %}
</div>
<div class="container" align="center">

    <h3>ADMIN PANEL</h3>
    <div class="row">
        <div class="col-md-12">
            
                <div class="col-md-12">
                    <div class="dropdown">
                        <button onclick="myFunction()" class="dropbtn">Filtrele</button>
                        <div id="myDropdown" class="dropdown-content">
                        <form method="get" class="dropdown-form"> 
                          <input type="text" placeholder="Search.." value="{% if myFilter.form.title.value == None %}{% else %}{{myFilter.form.title.value}}{% endif %}" name="title" id="id_title" onkeyup="filterFunction()"> <br>
                          <input type="text" placeholder="İl" name="il" id="id_il" value="{% if myFilter.form.il.value == None %}{% else %}{{myFilter.form.il.value}}{% endif %}" /> <br>
                          <input type="text" placeholder="İlçe" name="ilce" id="id_ilce" value="{% if myFilter.form.ilce.value == None %}{% else %}{{myFilter.form.ilce.value}}{% endif %}" /> <br>
                          <input type="text" placeholder="Mahalle" name="mahalle" id="id_mahalle" value="{% if myFilter.form.mahalle.value == None %}{% else %}{{myFilter.form.mahalle.value}}{% endif %}" /> <br>
                          <select name="start_created_date" id="id_start_created_date" value=""> <br>
                            {% if myFilter.form.start_created_date.value %} 
                            <option value="{{myFilter.form.start_created_date.value}}" selected disabled>{{myFilter.form.start_created_date.value}}</option>
                            {% else %}
                            <option value="" selected disabled>Bu Tarihten Sonra</option> 
                            {% endif %}
                            <option value="today">Bugün</option>
                            <option value="yesterday">Dün</option>
                            <option value="week">Son 7 Gün</option>
                            <option value="month">Bu Ay</option>
                            <option value="year">Bu Yıl</option>
                          </select><br>
                          <input type="number" placeholder="Bu Fiyattan Sonraki" name="start_price" step="5000" id="id_start_price" value="{{myFilter.form.start_price.value}}" /> <br>
                          <input type="number" placeholder="Bu Fiyattan Önceki" name="end_price" step="5000" id="id_end_price" value="{{myFilter.form.end_price.value}}" />  <br>
                          <button type="submit" class="btn btn-outline-success" style="float:center;margin-top:5px;width:100px;margin-bottom:2px;">Ara</button>
                        </form>
                        </div>
                      </div>
                </div>
        </div>
        <div class="col-md-12">
            <table class="table table-striped" style="text-align:center;margin-top:15px;">
                <tr>
                    <th></th>
                    <th>İlan Başlığı</th>
                    <th>Metre Kare</th>
                    <th>Fiyat</th>
                    <th>Yayınlanma Tarihi</th>
                    <th></th>
                </tr>
            {% if ilanlar %}
                {% for ilan in ilanlar %}
                <tr id="{% url 'gayrimenkul:detail' ilan.slug %}" onclick="onClickFunction(this.id)">
                    <td><img width="100px" height="100px;" src="{{ilan.get_image_or_default}}"/></td>
                    <td>{{ilan.title}}</td>
                    <td>{{ilan.mkare}}</td>
                    <td>{{ilan.price}}₺</td>
                    <td>{{ilan.created_date}}</td>
                    <td><a href="{% url 'gayrimenkul:update' ilan.slug%}" class="btn btn-sm btn-outline-warning"><i class="far fa-edit"></i></a>  <br>
                    <a href="{% url 'gayrimenkul:delete' ilan.slug%}" class="btn btn-sm btn-outline-danger" style="margin-top:15px;" onclick="return confirm('Bu ilanı silmek istediğinize emin misiniz ?')"><i class="far fa-trash-alt"></i></a></td>
                </tr>
                {% endfor %}
            {% endif %}
            </table>
        </div>
        
    </div>
    {% if ilanlar.has_other_pages %}
		<nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if ilanlar.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ ilanlar.previous_page_number }}">&laquo;</a></li>
            {% else %}
            <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
            {% endif %}
            {% for i in ilanlar.paginator.page_range %}
                {% if ilanlar.number == i %}
                <li class="activate page-item"><span class="page-link">{{ i }}<span class="sr-only">(current)</span></span></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if ilanlar.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ ilanlar.next_page_number}}">&raquo;</a></li>
            {% else %}
            <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
            {% endif %}
        </ul>
		</nav>
        {% endif %}
 </div>
<hr>
<footer style="font-size:8px;color:lightgray;margin-top:10px;float:right;height:10px;">©2020 Adil Tuğrul Haydar</footer>
  </body>
</html>
<script>
    function onClickFunction(parametre){
        window.location = parametre;
    }



function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

function filterFunction() {
  var input, filter, ul, li, a, i;
  input = document.getElementById("id_title");
  filter = input.value.toUpperCase();
  div = document.getElementById("myDropdown");
  a = div.getElementsByTagName("a");
  for (i = 0; i < a.length; i++) {
    txtValue = a[i].textContent || a[i].innerText;
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      a[i].style.display = "";
    } else {
      a[i].style.display = "none";
    }
  }
}
</script>

<style>

  .comboBox{
    padding: 5px;
    margin-top:20px;
  }
	table tr td:nth-child(2){
		color:blue;
		text-decoration:underline;
	}
	table tr:hover{
		background-color:lightblue !important;
		cursor:pointer;
	}
	table tr:first-child:hover{
		background-color:lightgray !important;
		cursor:auto;
	}

  .dropbtn {
  background-color: rgba(50,50,60,0.1);
  color: black;
  padding: 16px;
  font-size: 16px;
  border: none;
  cursor: pointer;
  width:500px;
}
.dropdown{
  padding: 5px;
}
.dropbtn:hover, .dropbtn:focus {
  background-color: rgba(50,100,100,0.4);
}

#id_title {
  box-sizing: border-box;
  background-position: 14px 12px;
  background-repeat: no-repeat;
  font-size: 16px;
  padding: 14px;
  border: none;
  border-bottom: 1px solid #ddd;
  width: 200px;
  
  border-radius: 10px;
}

#id_title:focus {
  outline: 3px solid rgba(0,120,250,0.7);
  border-radius: 10px;
  }

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f6f6f6;
  min-width: 500px;
  overflow: auto;
  border: 1px solid #ddd;
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}
#id_title, #id_il, #id_ilce, #id_mahalle, #id_start_created_date, #id_start_price, #id_end_price{
  margin:1px;
}
#id_start_created_date{
  width:182px;
}
.dropdown a:hover {background-color: #ddd;}

.show {display: block;}
</style>

templates/adminPanelUser.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Bootstrap CSS -->
    <link rel="shortcut icon" type="image/png" href="/media/favicon.png"/>
     <link href="{% static 'fontawesome-free-5.13.0-web/css/all.css' %}" rel="stylesheet">
    <title>Gayrimenkul</title>
  </head>
  <body>
  
	{% if request.user.is_admin %}
	<nav class="navbar navbar-expand-sm navbar-light bg-light">
	  <a class="navbar-brand" href="/">Gayrimenkul</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
		
		  <li class="nav-item">
			<a class="nav-link" href="{% url 'administrator:administrator' %}">İlanlar</a>
		  </li>
		  <li class="nav-item">
			<a class="nav-link" href="{% url 'administrator:users' %}">Kullanıcılar</a>
		  </li>
		 
		</ul>
		<ul class="navbar-nav ml-auto"> 
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user:userPanel' request.user%}">{{request.user}}</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user:code' %}">Üye Davet Kodu</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</a>
			</li>
		</ul>
	  </div>
	</nav>
	{% endif %}
<div class="container" style="margin-top:15px;text-align:center;width:100%;">
{% include 'messages.html' %}
</div>
<div class="container" align="center">
    <h3>ADMIN PANEL</h3>
    <div class="row">
        <div class="col-md-12">
                <div class="col-md-12">
                    <div class="dropdown">
                        <button onclick="myFunction()" class="dropbtn">Filtrele</button>
                        <div id="myDropdown" class="dropdown-content">
                        <form method="get" class="dropdown-form"> 
                          <input type="text" placeholder="Kullanıcı Adı Giriniz.." value="{% if myFilter.form.username.value == None %}{% else %}{{myFilter.form.username.value}}{% endif %}" name="username" id="id_username" onkeyup="filterFunction()"> <br>
                          <select name="timestamp" id="id_timestamp" value=""> <br>
                            {% if myFilter.form.timestamp.value %} 
                            <option value="{{myFilter.form.timestamp.value}}" selected disabled>{{myFilter.form.timestamp.value}}</option>
                            {% else %}
                            <option value="" selected disabled>Bu Tarihten Sonra</option> 
                            {% endif %}
                            <option value="today">Bugün</option>
                            <option value="yesterday">Dün</option>
                            <option value="week">Son 7 Gün</option>
                            <option value="month">Bu Ay</option>
                            <option value="year">Bu Yıl</option>
                          </select><br>
                          Admin : <input type="checkbox" name="admin"  id="id_admin" {% if myFilter.form.admin.value == True %}checked {% endif %}value="true" /> <br>
                          Aktif : <input type="checkbox" name="active"  id="id_active" {% if myFilter.form.active.value == True %}checked {% endif %}value="true" />  <br>
                          Staff : <input type="checkbox" name="staff" id="id_staff" {% if myFilter.form.staff.value == True %}checked {% endif %}value="true" />  <br>
                          <button type="submit" class="btn btn-outline-success" style="float:center;margin-top:5px;width:100px;margin-bottom:2px;">Ara</button>
                        </form>
                        </div>
                      </div>
                    
                </div>
        </div>
        <div class="col-md-12 col-sm-12">
        
            <table class="table table-striped" style="text-align:center;margin-top:15px;">
                <tr>
                    <th>Username</th>
                    <th>Tam Adı</th>
                    <th>Email</th>
                    <th>Cep Telefonu</th>
                    <th>İş Telefonu</th>
                    <th>Aktif</th>
                    <th>Admin</th>
                    <th>Staff</th>
                    <th>Kayıt Tarihi</th>
                    <th></th>
                </tr>
            {% if kullanicilar %}
                {% for user in kullanicilar %}
                <tr id="{% url 'user:userPanel' user.username %}" onclick="onClickFunction(this.id)">
                    
                    <td>{{user.username}}</td>
                    <td>{{user.full_name}}</td>
                    <td>{{user.email}}</td>
                    <td>{{user.cep_telefonu}}</td>
                    <td>{{user.is_telefonu}}</td>
                    <td>
                    {% if user.active %}
                      <i class="far fa-check-circle"></i>
                    {% else %}
                      <i class="far fa-times-circle"></i>
                    {% endif %}</td>
                    <td>{% if user.admin %}
                     <i class="far fa-check-circle"></i>
                    {% else %}
                      <i class="far fa-times-circle"></i>
                    {% endif %}</td>
                    <td>{% if user.staff %}
                      <i class="far fa-check-circle"></i>
                    {% else %}
                      <i class="far fa-times-circle"></i>
                    {% endif %}</td></td>
                    <td>{{user.timestamp}}</td>
                    <td><a href="#" class="btn btn-sm btn-outline-warning"><i class="far fa-edit"></i></a>  <br>
                    <a href="#" class="btn btn-sm btn-outline-danger" style="margin-top:15px;" onclick="return confirm('Bu ilanı silmek istediğinize emin misiniz ?')"><i class="far fa-trash-alt"></i></a></td>
                </tr>
                {% endfor %}
          {% endif %}
            </table>
        </div>
        
    </div>
    {% if kullanicilar.has_other_pages %}
		<nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if kullanicilar.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ kullanicilar.previous_page_number }}">&laquo;</a></li>
            {% else %}
            <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
            {% endif %}
            {% for i in kullanicilar.paginator.page_range %}
                {% if kullanicilar.number == i %}
                <li class="activate page-item"><span class="page-link">{{ i }}<span class="sr-only">(current)</span></span></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if kullanicilar.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ kullanicilar.next_page_number}}">&raquo;</a></li>
            {% else %}
            <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
            {% endif %}
        </ul>
		</nav>
        {% endif %}
 </div>
<hr>
<footer style="font-size:8px;color:lightgray;margin-top:10px;float:right;height:10px;">©2020 Adil Tuğrul Haydar</footer>
  </body>
</html>
<script>
    function onClickFunction(parametre){
        window.location = parametre;
    }

function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

function filterFunction() {
  var input, filter, ul, li, a, i;
  input = document.getElementById("id_username");
  filter = input.value.toUpperCase();
  div = document.getElementById("myDropdown");
  a = div.getElementsByTagName("a");
  for (i = 0; i < a.length; i++) {
    txtValue = a[i].textContent || a[i].innerText;
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      a[i].style.display = "";
    } else {
      a[i].style.display = "none";
    }
  }
}
</script>

<style>
	table tr td:nth-child(2){
		color:blue;
		text-decoration:underline;
	}
	table tr:hover{
		background-color:lightblue !important;
		cursor:pointer;
	}
	table tr:first-child:hover{
		background-color:lightgray !important;
		cursor:auto;
	}

  .dropbtn {
  background-color: rgba(50,50,60,0.1);
  color: black;
  padding: 16px;
  font-size: 16px;
  border: none;
  cursor: pointer;
  width:500px;
}
.dropdown{
  padding: 5px;
}
.dropbtn:hover, .dropbtn:focus {
  background-color: rgba(50,100,100,0.4);
}

#id_username {
  box-sizing: border-box;
  background-image: url('searchicon.png');
  background-position: 14px 12px;
  background-repeat: no-repeat;
  font-size: 16px;
  padding: 14px;
  border: none;
  border-bottom: 1px solid #ddd;
  width: 200px;
  
  border-radius: 10px;
}

#id_username:focus {
  outline: 3px solid rgba(0,120,250,0.7);
  border-radius: 10px;
  }

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f6f6f6;
  min-width: 500px;
  overflow: auto;
  border: 1px solid #ddd;
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}
#id_username, #id_admin, #id_active, #id_staff, #id_timestamp{
  margin:1px;
}
#id_timestamp{
  width:182px;
}
.dropdown a:hover {background-color: #ddd;}

.show {display: block;}
</style>

templates/login.html
{% extends "main_page.html" %}
{% load crispy_forms_tags %}

{% block icerik %}
<body style = background-color:midnightblue;color:White;>
<div class="container">
    <h3>Giriş Yap</h3>
    <hr style="background:White;">
  <div class="row">
    <div class="col">
      <form method = "post">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type = "submit" class = "btn btn-primary">Giriş Yap</button>
    </div>
    
    </form>
  </div>
  <br>
  <div class="col"> 
        Eğer bir hesabın yoksa, <a href="/user/register">Kayıt Ol</a>
    </div>
</div>
</body>
<style>
 #id_username, #id_password{
   border-radius:10px;
   padding: 3px 5px;
   margin: 2px;
 }
</style>

{% endblock %}

templates/main_page.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Bootstrap CSS -->
     <link rel="shortcut icon" type="image/png" href="/media/favicon.png"/>
     <link href="{% static 'fontawesome-free-5.13.0-web/css/all.css' %}" rel="stylesheet">
    <title>Gayrimenkul</title>
  </head>
  <body>
  {% if request.user.is_authenticated %}
    {% include "navbar.html" %}
  {% endif %}
<div class="container" style="margin-top:15px;text-align:center;width:100%;">
{% include 'messages.html' %}
</div>

{% block icerik %}

{% endblock icerik %}
<hr>
<footer style="font-size:8px;color:lightgray;margin-top:10px;float:right;height:10px;">©2020 Adil Tuğrul Haydar</footer>
  </body>
</html>

templates/navbar.html
	<nav class="navbar navbar-expand-sm navbar-light bg-light">
	  <a class="navbar-brand" href="/">Gayrimenkul</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
		  <li class="nav-item">
			<a class="nav-link" href="{% url 'gayrimenkul:create' %}">İlan Oluştur</a>
		  </li>
		  <li class="nav-item">
			<a class="nav-link" href="{% url 'gayrimenkul:list' %}">İlanları Görüntüle</a>
		  </li>
		</ul>
		<ul class="navbar-nav ml-auto"> 
			{% if request.user.is_authenticated %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user:userPanel' request.user %}">{{request.user}}</a>
			</li>
			{% if request.user.is_admin %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user:code' %}">Üye Davet Kodu</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'administrator:administrator' %}">Yönetici Paneli</a>
			</li>
			
			{% endif %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</a>
			</li>
			{% endif %}
		</ul>
	  </div>
	</nav>

templates/register.html
{% extends "main_page.html"%}
{% load crispy_forms_tags %}

{% block icerik %}


<div class="row" style="margin-top:10px;">
  <div class="col-md-6 offset-md-3">
        <h3>Register</h3>
    <hr style="background:white;">
     <form method="post" id="new_user_form">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type="submit" class ="btn btn-danger">Register</button>
    </form>
  </div>
</div>

{% endblock icerik %}